ladjs/superagent

lib/client.js

getXHR -> request.getXHR so you can redefine your own XHR if needed

getXHR made public

---

lib/node/index.js
test/node/pipe-redirect.js

Fixed redirect support for pipe method, I've stumbled on this issue for a while.  
Max redirects can be set with .redirects(n), just be the same with 'end' method.
Hope this helps.  :smile:

Fix redirect support for pipe method.

---

lib/node/index.js
test/node/redirects.js

Redirect to a correct path for relative location paths

---

lib/client.js
superagent.js
test/client/request.js
test/support/server.js

The API changed somehow and here is another take on #393 against the current HEAD.

xhr2 file download take two

---

docs/index.md

The last few docs updates hadn't updated the markdown files too, so I've added them in too :)
* 6c0919d728f0bb0c06aa7e2cc83b7b7686f3be49
* 3780559bd89abf98188813e740ada1297852d7dc
* 79cf516b20162fab1d0ec652b6ed2d96e512ffb8
* cb6ae8b60a59478f095ce4897696ad3d838dd48c

markdown source had drifted from the compiled html

---

History.md

mention change to handling of non-200 HTTP responses

---

lib/client.js

Would this be a reasonable solution in place of #538?

Adds progress events to downloads

---

History.md

I know this is the lamest of PRs...

Fix typo in History.md

---

lib/node/index.js
test/node/redirects.js

This PR is very similar to #408 (Fix 307 redirects). 
In fact most things were already in place and I've only ...
* ... added 308 to the list of known redirect codes
* ... added a short comment to indicate that 308 is handled
* ... copied the 307 tests and changed it simply to 308

Add support for 308 redirects (similar to 307)

---

Readme.md

Adding https://github.com/M6Web/superagent-mock

Update existing plugins section of readme.

---

.gitignore

.idea directory is generated by WebStrom

add ./idea to .gitignore

---

lib/node/index.js
test/node/basic.js

I recently ran into the issue fixed by pull request #540. The pull request was missing tests, so I added them.

fix incorrect content-length of data set to a Buffer object

---

lib/client.js
test/client/request.js

Request data serialization accounts for charsets in Content-Type header

---

Readme.md

Adding my superagent plugin to the plugin list.

Adding a plugin

---

lib/client.js
test/client/request.js
test/node/basic.js

Hey, I noticed missing statusCode on client side.

Add missing statusCode in client response

---

Readme.md

Added superagent-jsonapify addon to the list

---

docs/index.md

Okay added some docs for generators. I wasn't sure what `markdown`:
is being referred to here. I don't have that lib installed. But here are some docs. They'll need to be rebuilt.

add generator docs

---

test/node/toError.js

Use weirder port to avoid 8888 collision

---

docs/index.md

Fixed example in the documentation of the first page. Fixes #772

---

lib/client.js
test/client/request.js
test/support/server.js

Fix ie11 sends 'undefined' string if data was undefined. Issue #632

---

lib/client.js

fix syntax in req.send API docs

---

lib/client.js
lib/node/index.js
test/client/request.js
test/node/json.js

Fix serialize for responding custom JSON content-types

---

lib/node/index.js
test/node/multipart.js

Added 'progress' event on file/form upload in Node

---

bower.json

From the conversations I found in #315 and #387 (and a few other issues), it seems like you guys are ok with a minimal `bower.json` file, but no one has met your requirements for that yet.
I found the [current spec for bower.json](https://github.com/bower/spec/blob/master/json.md) from the Bower team. `name` is the only required field. `main` is useful for build scripts.

Added Bower manifest

---

lib/client.js
lib/node/parsers/json.js
test/client/request.js
test/node/json.js
test/support/server.js

This commit includes:
- Fix for #675
- Test to verify the code change.

675: Return raw response if the parsing fails

---

test/node/toError.js

let server pick port for toError test

---

test/basic.js
test/content-type.js
test/json.js
test/node/basic-auth.js
test/node/basic.js
test/node/multipart.js
test/support/server.js

Another batch. 
It has uncovered some incompatibilities, which for now I've disabled in browser with `if (doesntWorkInBrowserYet) {}`

Move tests

---

lib/node/index.js
test/use.js

change set header function, not call this.request() until call this.end()

change set header function, for issue #828

---

test/node/multipart.js

These were failing when I had something else around listening on 3005.

use free TCP port during tests

---

lib/node/response.js

remove parseCookies dead code

---

.travis.yml

Test latest stable and LTS. Don't test old unstable.

Update node versions used in test

---

lib/client.js
lib/is-object.js
lib/node/index.js
lib/request-base.js

extract common code for get/set/unset/getHeader to request-base.js
extract is-object to standalone commonjs module
fixes #873
part of #830

header management API consistency

---

lib/client.js
lib/node/index.js
lib/request-base.js

deal with root/globals
document both browser and node "val" param types
part of #830

extract field method to request-base

---

package.json
test/node/multipart.js

Update form-data to 1.0

---

lib/client.js
lib/node/index.js
lib/request-base.js

extract .withCredentials() to request-base

---

lib/client.js
lib/node/agent.js
lib/node/index.js
lib/node/response.js

Rename @api private properties to _prefixed

---

lib/client.js
test/basic.js
test/support/server.js

Allows to send queries with OPTIONS HTTP method

support OPTIONS requests in client #544

---

package.json
test/node/query.js

I didn't address the myriad of other outdated dependencies, but can if that would be useful.
Closes #908.

Upgrade the qs package

---

lib/client.js
lib/node/index.js
lib/node/part.js
lib/request-base.js
package.json

Should fix problem with formData.on in browsers

Polymorphic construction

---

lib/node/index.js

Avoid inconsistencies when callbacks for the redirect event modify url or headers

Handle modified redirects

---

docs/index.md
lib/client.js
lib/request-base.js
test/client/request.js

Rename ambiguous .parse to .serialize

---

Readme.md

Heya,
I know there's a couple of stubbing plugins already on the list, but I ended up writing one that better fits my workflow. Would be great if you could add it to the list. Thanks for the great module!

add link to superagent-httpbackend

---

lib/node/index.js
test/node/inflate.js

Fixes issue https://github.com/visionmedia/superagent/issues/857

handle HTTP status 204 with content-encoding: gzip

---

lib/client.js
test/json.js

Parse vnd+json

---

bower.json

Remove trailing comma from bower.json

---

Readme.md

These are what I could reverse engineer from the code. Additions welcome especially by bower/component users.

additional developer docs around packaging/publishing

---

lib/client.js
lib/is-object.js
test/form.js
test/node/form.js
test/support/server.js

One of few fixes needed for #973

Form serialize

---

lib/node/index.js
test/node/pipe.js

Emit response event when piping

---

docs/index.md

document browser version in electron

---

lib/node/index.js

Wait for parsers to avoid double callback

---

lib/client.js

Reorg try/catch

---

component.json
lib/client.js
package.json

Remove reduce component

---

Readme.md

add superagent-charset to plugins on README.md

README: add superagent-charset

---

lib/client.js
lib/node/index.js
test/client/request.js
test/client/serialize.js
test/node/query.js

In order to match the behavior of browser environment.

Skip null querystring values in node environment.

---

lib/client.js

I didn't realise we had upload progress, it was just buggy.
#977

Correct event.direction in uploads

---

lib/request-base.js
test/form.js

req.field assert

---

lib/request-base.js

Fixes an issue introduced by #1066

Fix error in null checking

---

lib/client.js
lib/node/index.js

Support the full `attach` options parameter in the node version too.

---

lib/client.js
lib/node/index.js
lib/request-base.js
test/client/serialize.js
test/node/form.js

Use specialized versions of isHost

---

docs/index.md
index.html

Document Facebook Accept header gotcha

---

lib/client.js
lib/node/index.js

Don't allow unsupported mixing of data types

---

lib/client.js
lib/node/index.js
lib/request-base.js

Superficial parity with browser API

responseType in Node

---

Makefile
lib/node/index.js
lib/node/unzip.js
test/node/multipart.js
test/node/parsers.js
test/support/server.js
test/timeout.js

Double callback parser fix

---

lib/request-base.js

I'm sending data to different backends and found I need to be able to set withCredentials. My alternative is to duplicate the entire call to superagent. Fingers crossed.

conditional withCredentials

---

lib/node/index.js
test/node/image.js

The responseType property wasn't read from the correct object so it wasn't taken into account.

Read responseType property from the correct object

---

docs/index.md

Fix a typo

---

lib/node/index.js

Add setNoDelay method for Request, this method can enable `TCP_NODELAY` option.

support TCP_NODELAY option

---

lib/node/index.js

Fix documentation around attaching Buffer

---

lib/client.js

The dangling comma causes an error in IE9

Remove dangling comma's

---

lib/response-base.js
test/node/flags.js
test/support/server.js

Set flags for response statuses `201` & `422`, since they are also quite commonly used.

Add flags for 201 & 422 response statuses

---

src/node/index.js
test/request.js
test/support/server.js

Reverts visionmedia/superagent#1460

Revert "Avoiding to set the "Content-Length" header for GET requests"

---

HISTORY.md

Per https://github.com/visionmedia/superagent/issues/1498#issuecomment-504126056

Add reference to GitHub releases page

---

docs/index.md

Changed default trie to 1 in documentation to reflect code
https://github.com/visionmedia/superagent/issues/1506

Fix issue #1506 regarding documentation for default tries

---

README.md

Added https://github.com/webuniverseio/superagent-node-http-timings to readme

Add plugin for measuring http timings in node

---

src/request-base.js
test/timeout.js

fix: throw timeout error in promise interface when timedout

---

docs/index.md

Taken from here:
https://github.com/visionmedia/superagent/blob/a009ace8b7ca9c68f619d729f9befe3e166d2c46/src/request-base.js#L480-L482

Add mention of bearer auth to docs

---

package.json

Reverts visionmedia/superagent#1661

Revert "#1660: Fix engines syntax in package.json"

---

.husky/commit-msg
.husky/pre-commit
package.json

Fix broken husky hooks. (Broken since https://github.com/visionmedia/superagent/commit/3c9c0f7feef61328131ae43b06e628bce1c20c17 (15 Feb))

chore: fix husky hooks

---

docs/index.md
docs/zh_CN/index.html
docs/zh_CN/index.md
index.html

Translated from English documents

Added Chinese document (添加中文文档)

---

docs/index.md

This is more semantic, SEO, and easier to read

added proper js formatting to all the code blocks  docs/index.md

---

src/node/response.js

Refs: https://github.com/nodejs/node/pull/39520#issuecomment-889697136

lazy access body
