lib/node/index.js
package.json

Now it'll behave the same way that the querystring does by default and
should work with more parsers.

Don't index array keys in querystring

---

lib/client.js
test/client/request.js

When passing a host object such as a File or FormData to `send()`, it identifies the data as being an object. Since no `Content-Type`-header is set (and should not be set, if we want the browser to automatically construct a `multipart/form-data`-request with boundaries and all), superagent currently sets the `Content-Type` to JSON. This overrides the browsers constructed boundary, and the server is unable to parse the request.
This PR adds an `isHost()` check to prevent setting the wrong content type, and also adds a test to ensure we don't encounter any regressions. 
Please let me know if you want anything changed (method of doing this, coding style etc).

Do not set Content-Type for host objects

---

test/node/redirects.js

Previously `res` was not defined when `.send` was called and this caused the test to fail for me locally, although travis looks fine.
What was there previously didn't really make sense to me, but maybe I'm missing something?

Fixes a locally failing server test

---

.zuul.yml
package.json
test/basic.js
test/client/request.js
test/client/xdomain.js

- Includes a `btoa` polyfill for the basic auth test -- where should we note that this is necessary for basic auth in IE9?
- Switches a `should` on a number to an `assert` -- failed on IE9
- Doesn't run the `PATCH` test on IE9 (feature detection) due to a weird response indicating that a Jetty server doesn't support the method -- this is likely a SauceLabs issue
- Doesn't run the xdomain failure test (feature detection) as afaik this isn't really supported atm and fails on IE9
Client tests are passing, but I'm getting a server test fail (also on master, though).
Thoughts?
@defunctzombie

Re-enable IE9 tests

---

lib/node/index.js
test/node/redirects.js

Adds tests that `307` redirects with the same method.
Note, this is not really a perfect implementation. The specification says that anything other than `HEAD` or `GET` must not automatically redirect, which is what this does.
Ideally, we should add a feature similar to `-L` on `curl` which tells superagent that we trust the site and is willing follow `POST`, `PUT`, etc. redirects. Ie. it should be an option, or a user-supplied called back that is used to decide if a 307 redirect should be followed with anything other than `GET` or `HEAD`.
Note, automatically following a 307 `PUT` with a `GET` as superagent didn't before is all bad. If interested I would happily implement a `.trustRedirect(true || false)` option. Other (better) names for such a option would be great though :)

Fix 307 redirects

---

.zuul.yml
test/client/request.js
test/client/xdomain.js

Blacklisted a couple tests have some weird errors, presumably from SauceLabs as they result in Jetty error messages.
`make test-browser` all green.

Add IE11 back to tested browsers

---

test/node/redirects.js

No more arity checks in the `.end()` callback.

Fix node redirect test cases

---

lib/node/index.js
test/node/basic.js

Implemented the `request.post(url, data, fn)`-type shorthand for all method functions.
Unsure if this is the best place to add the new tests.
Fixes https://github.com/visionmedia/superagent/issues/172
cc @defunctzombie

Make method function shorthand consistent

---

Readme.md

Mention of `window.btoa` polyfill for old IE.
Adds the section discussed in https://github.com/visionmedia/superagent/issues/220
cc @defunctzombie

Added supported browsers readme section

---

lib/client.js
test/client/request.js

This way we can avoid awkward OPTIONS requests.
Should deal with https://github.com/visionmedia/superagent/issues/442
cc @defunctzombie

Add xhr upload listener only if present on the request

---

lib/client.js
lib/node/index.js
test/basic.js
test/client/request.js
test/node/agency.js
test/node/flags.js

Any completed response (non network error) also results in the error
argument being provided to the end callback. This make it easier to
handle successful responses versus failed responses. Along with the
error argument, the response argument is also supplied.
This behavior does not currently extend to `pipe()`, only to buffered
responses that are parsed in full.
see this issue for context: #283

Always provide an error argument for non-successful responses

---

lib/node/index.js
test/node/json.js

If no Content-Type is specified by the server, superagent does not set the MIME type and the response does not get parsed at all. Neither `response.body` nor `response.text` are set.
[RFC1341](http://www.w3.org/Protocols/rfc1341/4_Content-Type.html) (or simply [Wikipedia](http://en.wikipedia.org/wiki/MIME)) documents that the default MIME type should be `text/plain` (superagent defaults to an empty string).
Using this patch, superagent can now fill the response with the default text parser even if the server does not set the Content-Type.
I had to fix the "no-content" test, since `res.text` is now filled with the empty string when no Content Type is specified. This sounds ok to me and to the RFC but **may be considered an API breakage**. Please review.
Also, 2 other tests are failing, but …

Set the default response mime type to text/plain as specified by RFC1341.

---

lib/client.js
test/client/request.js

We should never be looking at `xhr.response` on IE9 and other non-xhr2 browsers.
Also only running the xhr2 file download test where xhr2 is available (effectively excluding the test on IE9)
cc @defunctzombie

Fix responeType checks without xhr2 and ie9 tests

---

lib/node/index.js
test/node/agency.js

Now calling the end callback manually so that the end callback handler doesn't superseed cookie saving logic in `.on('response')`.

Fix: end callback called before saving cookies

---

lib/client.js

This pull request assumes the context of a Web Worker when both `window` and `this` are undefined. The global scope within a dedicated web worker is `self`, so we will just need set root to `self` in order for `root.XMLHttpRequest` to be found.
https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope

Add support for use within Web Workers

---

lib/client.js

Fixes failing `.noContent` test on IE9.
Just setting `.noContent` to use the possible falsy `1223` status code is not enough with the new error checking introduced, since `1223` is interpreted as an error (since it doesn't fit the proper status code range). 
I think we should just completely set any `1223` status to `204` (implemented in this PR). Alternatively we could specifically check for `1223` when determining if the status code is an error or not, but I feel like this is a better solution.
Thoughts @defunctzombie?

Fix IE9 204 status bug

---

Readme.md

The response handler is passed the error as the first argument,
not the response.

Correct broken Readme example.

---

package.json

SuperAgent depends on node-form-data@0.1.3, which uses node-mime@1.3.4 which has issues with webpack on the server-side (Ref: https://github.com/visionmedia/superagent/pull/615).
node-form-data@0.2.0 uses another library, mime-types@2.0.3, which does not have these issues.

Updates node-form-data dependency, 0.1.3->0.2.0, to fix webpack issue.

---

lib/client.js

React Native, is a browser-like environement but some browser properties
don't currently make sense in React Native. For example the location
object. However, we want our users to be able to use superagent, we even
recommend it on our website.
https://facebook.github.io/react-native/docs/network.html

[React Native Compat] Don't require window.location to be set

---

lib/node/index.js
test/node/redirects-other-host.js

Also added a bunch of test cases. And removed external requests to github in `redirects-other-host.js` tests, now using localhost with different ports for different hosts.
For some reason not deleting the `host` header causes bad things to happen...
I can't actually find the place where it fails to overwrite the host header with the hostname from the url. But it has got to be there somewhere.
Anyways, existing code depends on headers being deleted. So that probably a good solution.

Fix redirects to other hosts with 303, 307 and 308

---

package.json

The primary reason is that webpack has issues with including superagent on the server-side because in version 1.2.11, node-mime reads `./types/mime.types` and webpack does not recognize that dependency. In 1.3.4, it requires a `types.json` file which webpack can recognize.

Updates node-mime dependency. 1.2.11->1.3.4, to fix webpack issue.

---

Readme.md

Some users might not understand that the request will not be sent before calling `end` function. I hope this pull request is helpful to those users.

Explain what the end function does

---

Readme.md

According to the [superagent-prefix example in the repo](https://github.com/johntron/superagent-prefix/blob/master/example/index.js), the usage is only as an addition to the request chain, not as a file-wide prefix. The file-wide prefix returns an error currently. I've opened [an issue with superagent-prefix](https://github.com/johntron/superagent-prefix/issues/2) to see if this type of global usage is intended or available, but until then, this syntax should be corrected to reflect the plugin API.

Fixed Prefix usage

---

test/node/basic.js

A change introduced in
https://github.com/iojs/io.js/commit/abb00cc915b2e336afb73210298f673a00d
ad9f0 throws if the url being
formatted is not an object or a string.

Make tests pass on iojs

---

docs/index.md

docs: remove references to the deprecated Request.part()

---

lib/client.js

err will be always null in this case, because it's being checked on line 477 already
not a big deal, I just accidentally spotted this while reading the code :)

removed unnecessary err check

---

lib/client.js
lib/node/index.js
test/basic.js

This is helpful for working with co-routine control flow libraries like `co()`:
```js
var res = yield request
.get('http://localhost:8080')
.type('json')
```
No idea if I'm committing blasphemy in the promise world or if this will quiet the promise people down a bit. 
Don't really mind if this gets merged or not, but if people are happy with it, I'll add some tests.

lib: added fake promises

---

lib/node/index.js

Argument is named `res` but in function body it references `result`.

Fix typo in custom parser example

---

Readme.md

superagent-no-cache is published in NPM [under that same name](https://github.com/johntron/superagent-no-cache/blob/master/package.json#L2), as it is [with component](https://github.com/johntron/superagent-no-cache/blob/master/component.json#L2). Updated Readme to reflect that.

Corrected superagent-no-cache require statement

---

lib/node/index.js

This PR addresses #724. On a side note, code on the browser side is wildly different (this bug didn't seem to exist there).

Do not apply JSON heuristics if already have a valid parser

---

lib/client.js

`self` is compatible with Window and Web Workers (see [this article](https://developer.mozilla.org/en-US/docs/Web/API/Window/self)).
Checking for `this` is breaking browserify builds that run in Workers.
Another solution is to simply do `var root = self;`. What is the reason to have a fallback to `this` ?

Fix detection of root object

---

lib/client.js

Allows browser clients to override response parser (already allowed in node builds) (as part of #690)

Added Request#parse method to client build

---

lib/client.js
test/client/request.js

Added parse method to Request class instead of Response

Allow custom parser in Request [was: Fixes #740]

---

test/node/redirects.js

In io.js version 3.0.0 the text of HTTP response code 302 was changed from "Moved Temporarily" to "Found" to bring it in line with the specification. See [1]. In order to support older Node versions (0.10, 0.12), older io.js versions (1.0.0, 2.0.0), and future versions (io.js 3.0.0 and Node 4.0.0). I changed the test to look for either message. Now the tests are passing on all versions of Node that I mentioned. 
Note: this PR addresses the stacktrace part of issue #773 (Node 4 support), but does not resolve that issue. I'm still wondering what the policy is for superagent supporting current versions on Node including the LTS release. 
[1] https://github.com/nodejs/node/wiki/Breaking-Changes

Add "Found" to test. Tests now pass on io.js 3.0.0 and node.js 4.0.0

---

lib/client.js

a different format from #629 
I believe the option for array formatting should be eventually exposed to the user a la qs:
```js
Qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'indices' })
// 'a[0]=b&a[1]=c' 
Qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'brackets' })
// 'a[]=b&a[]=c' 
Qs.stringify({ a: ['b', 'c'] }, { arrayFormat: 'repeat' })
// 'a=b&a=c' 
```

fixes #670 - handles arrays better

---

lib/node/index.js
lib/node/parsers/json.js
package.json
test/node/inflate.js

- don't strip json before parsing (slow on large strings, not needed)
- fix error-triggering on corrupted compressed streams (issue #776)
This test is failing in master and is not fixed
```
1) request req.redirects(n) should alter the default number of redirects to follow:
Uncaught AssertionError: expected 'Found. Redirecting to /movies/all/0' to match /Moved Temporarily/
at Assertion.prop.(anonymous function) (/Users/jbellenger/workspace/superagent/node_modules/should/lib/should.js:60:14)
at /Users/jbellenger/workspace/superagent/test/node/redirects.js:232:25
at Request.callback (/Users/jbellenger/workspace/superagent/lib/node/index.js:797:3)
at IncomingMessage.<anonymous> (/Users/jbellenger/workspace/superagent/lib/node/index.js:993:12)
at emitNone (events.js:72:20)
at …
```

misc fixes found at twitter

---

.travis.yml

WIP - don't merge
Fixes #787 
I tested on https://travis-ci.org/olalonde/superagent but I'm getting this error on the browser test (could be a temporary bug with localtunnel.me):
```sh
- passed: <firefox 42 on Mac 10.8>
- queuing: <android 5.1 on Linux>
events.js:72
throw er; // Unhandled 'error' event
^
Error: connection refused: localtunnel.me:43772 (check your firewall settings)
at Socket.<anonymous> (/home/travis/build/olalonde/superagent/node_modules/zuul/node_modules/zuul-localtunnel/node_modules/localtunnel/client.js:84:32)
at Socket.emit (events.js:95:17)
at net.js:441:14
at process._tickCallback (node.js:448:13)
at Socket.Readable.on (_stream_readable.js:708:33)
at TunnelCluster.open (/home/travis/build/olalonde/superagent/node_modules/zuul/node_modules/zuul-localtunnel/node_modul …
```

travis: add node 4.0,4.1 and iojs to travis.yml

---

examples/simple-get.js

Added a valid `gist` link so `node examples/simple-get.js` can run successfully. This is to fix: https://github.com/visionmedia/superagent/issues/705

705: examples/simple-get.js url endpoint invalid

---

lib/client.js
lib/node/agent.js
lib/node/index.js
test/client/request.js

Addresses #605. This maintains support for 'del' while adding 'delete' so that it's not a breaking change. On the client side it maps the same function that was used for 'del' to both verbs. On the server side it adds 'del' to the list of methods if it isn't there and maps them both to the 'DELETE' request. Added a test for the client that's the same as del. Doesn't seem like this should be an issue with 'use strict' but I could easily add a test for that since it can be scoped to a function.

605: adds delete verb support and maintains del verb support

---

lib/node/index.js

Avoid the error which is emitted from 'socket hang up' to cause the `fn undefined error` on JS runtime.
while event `req.error` is emitted:
```
req.on('error', function(err){
// flag abortion here for out timeouts
// because node will emit a faux-error "socket hang up"
// when request is aborted before a connection is made
if (self._aborted) return;
self.callback(err);
});
```
because only `prototype.end()` and `prototype.redirect()` had assigned the value to `this._callback`, so if the `req.on('error')` event is fired -> `self.callback(error)`, it will cause `prototype.callback()` to throw the `undefined` runtime error.

Avoid the error which is emitted from 'socket hang up' to cause the fn undefined error on JS runtime.

---

lib/node/index.js
lib/node/utils.js
test/node/redirects.js

The problem case for this is cookie-based authentication. In my case the Wordpress REST API `/users/me` redirects to `/users/{id}` based on authentication. This works fine in the browser (it sends the cookies to the redirected path), but on the server superagent strips the cookies and the call to `/users/{id}` results in a 401 Unauthorized response.

Retain cookies on redirect when hosts match

---

lib/client.js

A backward-compatible fix for #484
I still think it should be changed to a completely different error in 2.0, but I also want to fix it quickly for 1.x users.

Avoid misleading CORS error message

---

Readme.md

I just built this plugin [superagent-serializer](https://github.com/zzarcon/superagent-serializer) to make serialization/convertion of server payload easier using superagent.
Hope you like and thanks for the lib! :heart_eyes_cat:

Add superagent-serializer to addons

---

lib/node/index.js
test/node/parsers.js

I'm downloading large sets of json files using superagent from a slow server. In some cases, I need to abort the request using `.abort()` method.
When the json is in the middle of the transfer, I get a syntax error when superagent tries to parse the partially transfered json string. 
I think that on aborted requests, the parser shouldn't throw any error.
Thanks for the good work, and let me know if I can help fixing this.

Fix to avoid throwing errors on aborted requests

---

lib/client.js

Please check if mergeable.
I want to use this nice library on Ie8 with no error...
(I know it supports `>=ie9`)
Thank you.

fix `delete` breaking on ie8

---

lib/node/index.js

Talking to certain servers I was seeing the following error, even when the response was 200 OK
```
Error: read ECONNRESET
at exports._errnoException (util.js:855:11)
at TCP.onread (net.js:544:26)
```

Don't let request error override responses

---

lib/node/index.js
test/node/basic.js

This is a fix for https://github.com/visionmedia/superagent/issues/586.
This change adds the equivalent of a no-op to the `Request` prototype, which simply returns `this`, as this method is irrelevant in a Node context.
I've also added a test for this, so hopefully this PR is pretty straightforward :)

Add "withCredentials" to Node API, fixes #586

---

lib/node/index.js
test/node/basic.js
test/support/server.js

Currently, if you pass an URL as string, the **query string is parsed and regenerated**.
On the one hand, this **introduces overhead**, because such parsing and generation is not necessary.
More importantly, however, it **destroys the original encoding of the passed URL**. Therefore, it is currently impossible to use superagent with servers that are sensitive to encoding. In particular, we cannot use superagent (and thus supertest) to verify whether a server correctly reacts to different encodings. For instance, if we want to try `http://example.org/a?q=(b)` and `http://example.org/a?q=%28b%29`, superagent would in both cases send `http://example.org/a?q=(b)` to the server.
This commit preserves the original URL encoding by adding the query string to `qsRaw` rather than `qs`.

Don't modify the query string, but preserve its encoding

---

lib/client.js
lib/node/index.js
test/node/multipart.js

Fixes #803. (The docs should be added during #807.)
So the client only emits `'progress'` during a download, and the node version only emits `'progress'` during an upload?
I was under the impression that the node version would emit `'progress'` during uploads and downloads, but it doesn't look like it does. And the changelog seems to back that up.
I wonder if `'upload'` and `'download'` are the wrong terms, because they imply where the request/response is going, but what we actually know is whether it is a request or a response.

Add 'direction' property to 'progress' events

---

lib/client.js
lib/node/index.js
test/client/request.js

This fixes #843 
I didn't add tests because I was unsure how to get them running. I got some error about no saucelabs credentials when I tried to run the tests.
__client__
I am assuming the file param is always expected to be a `File` object.
__node__
I am assuming the file param is expected to be an `fs.ReadStream` if not a string.

Default filename to files name

---

lib/node/index.js
test/node/query.js

Query string is missing from request path when using stream.pipe(request)
node repl test case:
```
var express = require('express'), fs = require('fs'), request = require('superagent');
express().put('/', function(req,res){ console.log("url=" + req.url) }).listen(3006);
fs.createReadStream('README.md').pipe(request.put('http://localhost:3006/?foo=bar'));
```
expected output: url=/?foo=bar
actual output: url=/
The problem: the query is appended to req.path in end() which is run after the 
headers have been sent when the request is treated as a writable stream, so the
path sent to the server is always missing the query.
My attempt at a fix: the first time write() is called, set a flag indicating
that the request is being treated as a writable stream.  If this is the case we 
need to append …

ensure query string is appended when doing stream.pipe(request)

---

lib/node/index.js
test/node/redirects.js

This might be related to other multipart/form-data issues.
It occurs when the "Content-Type" header is set to "multipart/form-data" during the request, followed by a redirect response from the server. In the code, a FormData instance is created during the POST request, but it's not cleared within the redirect function. This prevents the callback ( req.end(data) ) at around line 1070 from running and the script hangs.
```
formData.pipe(getProgressMonitor()).pipe(req);
});
} else {
req.end(data);
}
```
This is probably a temporary fix. I suppose there are cases where keeping the FormData around during the redirect might be desirable. 
Here's some standalone test code I was using.
```
var http = require('http');
var server = http.createServer(listener);
var superagent = …
```

Redirect after a multipart/form-data POST

---

lib/node/agent.js
lib/node/index.js

This is caused by superagent modifying the list of http methods coming from the 'methods' package. In npm 2.x this isn't usually a problem as superagent uses its own copy of the methods package, however in npm 3.x all packages are deduped, so express, superagent, and other libraries all share the same package. 
The fix is to create a shallow copy before modifying the list for superagents use so that other libraries are not affected.

Fixed conflict with express (and possibly other libraries) when using npm 3.x

---

lib/node/index.js
test/node/basic.js

a4ddd6a introduces case-sensitivity in header set(), get(), and unset(), which is inconsistent with Node HTTP module and the HTTP spec itself. It also borks some superagent addons such as [superagent-hawk](https://github.com/CrowdProcess/superagent-hawk/blob/master/index.js#L31).

Fix case-sensitivity in node header introduced by a4ddd6a

---

package.json

For a project of mine it is necessary, that all dependencies have license information.
Unfortunately superagents `extend` dependency does not contain any license information.
Therefore I bumped this dependency.

bump extend dependency due to missing license information

---

test/node/agency.js
test/node/basic-auth.js
test/node/flags.js
test/node/form.js
test/node/https.js
test/node/image.js
test/node/incoming-multipart.js
test/node/inflate.js
test/node/multipart.js
test/node/not-modified.js
test/node/parsers.js
test/node/pipe-redirect.js
test/node/pipe.js
test/node/query.js
test/node/redirects-other-host.js
test/node/redirects.js
test/node/response-readable-stream.js
test/node/timeout.js
test/node/toError.js
test/node/user-agent.js

When starting express servers in unit tests, always listen on a free
port.
This should solve port conflicts entirely, which were still plaguing me (I use a **lot** of ports, especially in 3xxx 4xxx ranges!).
It should also avoid theoretical race condition where server.listen()
takes a long time due to how we use `before`, although in practice
I don't believe this was ever occurring.
There's some boilerplate to do it right with mocha before, etc, but
it's OK.
One implicit interdependency between distinct tests was refactored.

avoid TCP port conflicts in all tests

---

lib/client.js
lib/node/parsers/json.js
test/client/request.js
test/json.js
test/support/server.js

In reference to issue #876, these changes will allow the client to access the http status code even when the JSON response body is malformed.
This is the same pull request as https://github.com/visionmedia/superagent/pull/877 but has been squashed into one commit instead of 6 as suggested by @pornel.

Adding statusCode to error response when JSON response is malformed

---

lib/client.js
lib/node/index.js
lib/request-base.js
lib/request.js

This takes any identical copy/paste code between
client code and node code and puts it in a common
superclass.
This handles the identical/easy cases.
Plan to handle the slightly different cases next.
Part of #830

extract common code into request-base object

---

Readme.md

Hi, I created a url suffix plugin. Surprisingly it did not exist. I have added it to the Readme.md after superagent-prefix.

Added superagent-suffix to existing plugins documentation

---

lib/client.js
test/client/request.js

Allows the following request to be made
```javascript
request
.get('http://d8d913s460fub.cloudfront.net/videoserver/cat-test-video-320x240.mp4')
.set('Content-Type', 'blob')
.end(function (err, res) {
console.log(err, res);
});
```

added support for blob and arraybuffer responseType

---

lib/client.js
test/client/request.js
test/support/server.js

Use native xhr auth on client because:
> Chrome supports four authentication schemes: Basic, Digest, NTLM, and Negotiate. 
I did check Digest auth on chrome it works
Why this lib did not use native authentication?

use native xhr auth on client

---

Readme.md

`superagent-use` makes is possible to apply plugins to all requests, instead of just a single request.
My usecase is that I use SuperAgent to request data from an API, which resides on another domain than the application itself. 
With this plugin I no longer have to set the hostname for every request, I simply add a global plugin.
Before:
```js
var superagent = require('superagent');
var prefix = require('superagent-prefix')('https://api.example.com');
superagent
.get('/')
.use(prefix)
.end(function(){});
superagent
.post('/auth')
.use(prefix)
.send({user: 'foo', pass: 'bar'})
.end(function(){});
// etc..
```
After:
```js
var superagent = require('superagent-use');
var prefix = require('superagent-prefix')('https://api.example.com');
superagent.use(prefix);
superagent
.get('/') …
```

Add link to superagent-use

---

lib/client.js
lib/node/index.js
lib/request-base.js

- Client code did not return `this` when `.abort()` was called on an
already-aborted instance. This was probably an unreported bug. Now
consistently returns `this` for chaining.
- internal state is called `_aborted` consistently. Any third party
code directly accessing `req.aborted` in the browser will break. This
property was and is an internal property and not a public API.
(heads up @jpodwys)

.abort() extracted to request-base

---

lib/request-base.js
test/basic.js

Turns out positioning of `this.clearTimeout()` matters in the browser.
Sorry for the churn on this one. I'm pretty confident it is finalized now.

test for multiple abort calls

---

lib/node/index.js
lib/request-base.js
test/basic.js
test/node/basic.js

This API is now present in both node and the browser.
It was node-only prior to this.
Docs improved and unit tests moved so it runs in node and browser.
Part of #830

extract .toJSON() to request-base

---

test/node/pipe-redirect.js
test/node/pipe.js

wait for destination stream to finish writing before reading it back to
verify
Suspect this will resolve flakyness of TravisCI tests.
See also #912 (which I think should now be closed without
merge)
(Sorry, created a new PR instead of #913 due to my git/github rebase-fu failing repeatedly. See #913 for the backstory and #912 will be closed)

fix race condition in pipe tests

---

History.md
bower.json
lib/request-base.js
package.json
test/client/request.js

Require form-data on-demand, so that it doesn’t throw when not in use

---

docs/test.html
package.json
test/node/agency.js
test/node/inflate.js
test/node/multipart.js
test/node/not-modified.js

Update to current latest version of all deps.
Consistently use semver major number only.
Code updates for removed should.js APIs.
Didn't update `qs` as that is trickier and being dealt with in a separate issue.

Dep semver updates

---

docs/index.md
lib/request-base.js
test/basic.js
test/support/server.js

Another take on Promises. 
* Uses global `Promise`. ES6 is final now, so I think it's OK to expect it for interoperability. 
Node 0.10—the IE6 of Nodes—can easily polyfill it.
* Re-returns the same result, so that usage of the request as thenable in multiple places won't make multiple calls. That's consistent with how real promises behave.
Fixes #722 Closes #852
#854 #726

Make .then() return a real Promise

---

docs/index.md

had an old link to Mocha homepage

fix a 404 in docs

---

Readme.md

that's for maintaining superagent, it's a great module. I wrote a plugin to throttle requests, was hoping for a mention in your readme.. thanks!

add superagent-throttle to plugins list

---

lib/client.js

Heya,
Server-side requests have this `_appendQueryString()` function, but client-side requests don't, so there's no consistent way for plugins to apply the query string. Makes things a little annoying for plugins that overwrite `Request.prototype.end()` like https://github.com/vkarpov15/superagent-httpbackend.
Thanks,
Val

refactor: add _appendQueryString to client request

---

lib/node/index.js

Now response is always created in the same way. 
Order of events is now more consistent:
* `end`, `response`, and callback — for *buffered* responses. Same in Node and browser
* `response`, `end`, and callback for unbuffered responses (pipe)

Deduplicate Response creation, order of events

---

lib/request-base.js
test/request.js

header is also important for inspect a request. as I'm using the `Authentication` header for auth. and I'm using this
```js
request
.get(url)
.set('foo', 'bar')
.then((err, res) => {
if(err) return next(err);
});
```
`next` is the `next` in express. I'd like to inspect the header too.

request-base: add header for inspect

---

lib/client.js

Fix runtime issue in 1.8.x branch when calling `abort` before the XHR have been created.

Fix calling abort before XHR setup

---

lib/node/utils.js

Superagent is overriding Node's `res.on` function, but forgetting to return `this` to maintain the original behavior.

Return this when overwriting the response object's on() method

---

test/basic.js

We can't only catch errors for request
```js
const superagent = require('superagent')
superagent
.get('https://ya.ru')
.catch(err => console.log(err))
```
Output:
```
.catch(err => console.log(err))
^
TypeError: superagent.get(...).catch is not a function
```
But in promises we can:
```js
Promise.reject('Error!')
.catch(err => {
console.log(err) // Error!
})
Promise.resolve(123)
.catch(err => {
// no errors
console.log(err)
})
```
---
Added test to reproduce error. I can try to fix it if you are ok with it.

The returned object is not compatible with Promises.

---

Readme.md

Superagent-cache is not yet compatible with superagent `2.x`. Adding a note so people using `2.x` aren't mislead.

Indicate which versions superagent-cache can use

---

Readme.md

Support added in 2.0.0 negates any utility and it's presence in this list implies that Promises are _not_ supported. This was pretty confusing to me, even though the docs on the site clearly communicate that Promises are now supported. I look at READMEs first and docs elsewhere a distant second.
I also somehow missed that news earlier this year and caught myself using thenables after forgetting to install the plugin in a project. Retracing my steps wondering why it was actually working, I discovered the good news!

Remove superagent-promise-plugin from plugin list

---

Readme.md
docs/index.md

I noticed that the spelling of SuperAgent was inconsistent in the docs. Sometimes it was `Super Agent`, sometimes `superagent`, sometimes `Superagent` and most often `SuperAgent`.
I normalized on `SuperAgent`, since that seemed to be the most consistent.

Normalize spelling of SuperAgent in docs

---

lib/request-base.js
test/node/multipart.js

Allows `.field()` to behave similar to `.set()` and handle an object to set multiple key-values. Would it also be desirable to have it handle arrays? i.e
The following:
```
req.field({ array: [1, 2, 3]  });
```
would translate to something like:
```
req.field('array', 1);
req.field('array', 2);
req.field('array', 3);
```
The underlying `form-data`'s `append()` does not support this and errors out as it feels this sort of call is ambiguous (multiple interpretations). Would this be inline with superagent or is it indeed too ambiguous? 
Also I could not find browser-side tests for `.field()`, is this intended?

enable field() to handle an object

---

docs/index.md
lib/node/index.js
test/node/unix-sockets.js

related: https://github.com/visionmedia/superagent/issues/779
I've implemented it. maybe this is not breaking change.

Support unix sockets

---

lib/node/index.js
package.json

recorded multiple memory leaks from superagent. This was from a 1.1 version, but the underlying problem was still the same. 
```
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
at IncomingMessage.addListener (events.js:239:17)
at IncomingMessage.Readable.on (_stream_readable.js:680:33)
at ClientRequest.<anonymous> (.../node_modules/superagent/lib/node/index.js:915:9)
```
```
at IncomingMessage.Readable.on (_stream_readable.js:680:33)
at IncomingMessage.once (events.js:265:8)
at IncomingMessage.Readable.pipe (_stream_readable.js:486:9)
at Object.exports.unzip (.../node_modules/superagent/lib/node/utils.js:90:7)
at ClientRequest.<anonymous> (.../node_modules/superagent/lib/node/index.js:825:13)
``` …

change .on to .once, prevent possible memory leaks

---

bower.json

The library relies on component-emitter but is not listed in the bower.json.
There are a few others too, just haven't run into issues yet.

Add component-emitter to bower.json

---

lib/client.js
lib/node/index.js
lib/request-base.js

This PR is an alternative solution to #1076
* Make RequestBase a constructor function
* Make it mixin its prototype functions when called as a function
* Unifies mixin approach with Emitter
* Fixes global scope issues in module bundlers like rollup.js
References #1076
See also:
https://github.com/rollup/rollup/issues/1007
https://github.com/rollup/rollup/pull/1023
https://github.com/rollup/rollup-plugin-commonjs/issues/127

Mixin RequestBase functions from a prototype

---

lib/client.js
lib/request-base.js

I recently had an issue where I would be making two consecutive POST request. Both received an object as `data` and both used a second `csrf` object. Something like:
```javascript
var csrf = extractCSRF();
request1 = (data) => {
return new Promise((resolve, reject) => {
request
.post(ENDPOINT_1)
.set(HEADERS)
.send(csrf)
.send(data)
.end((err, res) => err ? reject(err) : resolve(res.body));
});
}
request2 = (data) => {
return new Promise((resolve, reject) => {
request
.post(ENDPOINT_2)
.set(HEADERS)
.send(csrf)
.send(data)
.end((err, res) => err ? reject(err) : resolve(res.body));
});
}
```
The second request would fail because of conflicting parameters. The `csrf` object was being mutated due after the first request causing a merge conflict and a malformed request.
I was able to track …

Initialize request data

---

.zuul.yml
Makefile
package.json
test/basic.js
test/client/request.js
test/client/xdomain.js
test/content-type.js
test/json.js
test/redirects.js
test/request.js
test/use.js

- 20s timeouts
- latest zuul
- configure SAUCE_APPIUM 1.6
I was seeing our 10s timeouts exceeded a lot in sauce labs for slower browsers/OSes. Increasing to 20s seems empirically to help. :-/

saucelabs browser test tweaks

---

lib/client.js
test/client/request.js
test/support/server.js

responseText throws InvalidStateError when responseType is not 'text' or ''

Set xhr.response instead of xhr.responseText to err.rawResponse

---

lib/client.js
lib/node/index.js
lib/node/response.js
lib/node/unzip.js
lib/response-base.js
lib/utils.js
test/node/utils.js

Recently we were wondering why parsed `response.links` can be found in the node version of superagent, while not being there in the browser version, after a quick debugging session we found the reason why. In this PR we did the following things to get more parity between node and browser versions:
1.  split `lib/node/utils` into `lib/utils` and `lib/node/unzip`, so that `lib/utils` can be used in the browser code and does not bring unwanted dependencies (namely `unzip`) into the browser.
Maybe `lib/node/unzip` should be renamed to `lib/node/node-utils` or extend `lib/utils`, but this seemed to be the cleanest solution at the moment.
2.  After that we realized, that the client and node implementation of `Response` share a lot features and therefore moved the following shared functions of …

DRY Up Response in Node and Browser

---

lib/client.js
test/client/request.js

Previous test was incorrect. It was looking for error caused by Blob being accidentally parsed as JSON, which doesn't make sense when responseType was explicitly set to be Blob.

Blob should not cause parse errors

---

lib/client.js
test/client/request.js

client: handle `xhr.open()` errors

---

lib/request-base.js

Warn when using unsupported mix of send and field

---

lib/client.js
lib/node/index.js
lib/request-base.js
lib/should-retry.js
lib/utils.js
test/redirects.js
test/retry.js
test/support/server.js

I'm just opening this early sketch to see if there is interest in adding a `Request.retry` method. I'm aware of [segmentio/superagent-retry](https://github.com/segmentio/superagent-retry), but it relies on some hacky behaviour to reset state between attempts, and doesn't seem to work with newer versions of `superagent`. There would seem to be quite a bit of resetting necessary to make this work properly for errors, timeouts, and aborts, so I think it might be better done as a core method rather than a plugin.
In any case, I'd be happy to work on adding this if there is interest.
Progress:

[WIP] add `Request.retry`

---

docs/index.md

Found out that SuperAgent supported these methods from the [test documentation](http://visionmedia.github.io/superagent/docs/test.html) (which looks a bit outdated on the GitHub pages).
Thanks for SuperAgent, I use it (almost) everyday!

Add docs for HTTPS request

---

lib/client.js

endpoints with DELETE methods can accept a body in the request, we need this feature in superagent so we can use `supertest` to test delete endpoints.

Allow optional body/data in DELETE requests

---

lib/request-base.js
test/retry.js

I’m afraid I made a design error by disallowing setting retry count to `0`. This fix makes the following changes:
- passing `0/null/undefined/negative numbers` does not enable retry
- passing nothing or `true` defaults to `1` retry

validate retry() `count` and allow setting to 0

---

lib/node/index.js

I am attempting to set my own parser as follows:
```javascript
var jsdom = require('jsdom') ;
var request = require('superagent');
request.parse['text/html'] = function(res,fn) {
res.text = '';
res.setEncoding('utf8');
res.on('data', function (chunk) {
res.text += chunk;
});
res.on('end', function () {
jsdom.env({
html: res.text,
url: url,
done: function (err, window) { // res.body === window
console.log('parsed document') ;
fn(err, window);
}
});
});
} ;
var agent = request.agent() ; // Gimme cookies....
agent.get(url)
.buffer(true)
.then(...) ;
```
Without this PR, the `parsed document` string is never output as the default `text` parser is used, even when the mime type returned in the response is `text/html`. 
By switching the order of the logic for determining which parser to use (the …

Fixed being able to define own parsers when their mime type starts with text/

---

lib/client.js
lib/node/index.js

This would add bearer token support to the `auth` method (both for client and for node).
```js
.auth(accessToken, { type: 'bearer' })
```
Notice I made pass optional since bearer authorization doesn't need a 2nd argument.

Add bearer token support

---

lib/request-base.js

`.timeout({request:1000})` is an easy mistake to make.

Warn about bogus timeout options

---

lib/request-base.js
test/timeout.js

Add errno to distinguish between response timeout and body download timeout
The existing `err.code` can't be changed, since it'd technically be a breaking change.
The new `errno = ETIMEDOUT` code is almost exactly what it should be. The other `ETIME` is stretching the meaning "timer expired" a bit, but at least its still a valid posix code.

Errno for timeouts

---

lib/client.js
lib/node/index.js
test/basic.js

Hello everyone
An issue was filled on chai-http chaijs/chai-http#153
The issuer was adding a property to the prototype of Object which was making `superagent` throw a TypeError when setting a header. (I know you should not be adding properties to the prototype of Object, but the truth is that you can).
So, to prevent that for happening. This PR adds a check for `hasOwnProperty` before setting the header.
I also added a test that reproduces it.
Thank you 😄

Check for ownProperty before adding header

---

docs/index.md
lib/should-retry.js
test/client/xdomain.js

When using the retry() functionality on a bad connection, the browser can sometimes fail during a CORS OPTIONS request, which currently doesn't get retried. Superagent throws an error with crossDomain: true property in this case. We should retry instead, since the next attempt might succeed.

Allow crossDomain errors to be retried (#1194)

---

lib/client.js
lib/node/index.js
test/request.js
test/support/server.js

Partially addresses #534. Browser and node are now consistent for
both GET and HEAD, but only the shorthand APIs behave this way.

Send payload in query string for GET and HEAD shorthand API

---

Readme.md
docs/index.md

Also clarify in the docs that the default example sends a JSON upload,
not a form-urlencoded upload.

Fix spelling mistake in the docs

---

package.json

https://github.com/visionmedia/superagent/blob/master/History.md#300-2016-11-19

Update supported node version to >= 4.0

---

docs/index.md

I wanted to use superagent to send an HTML form, because of some `<input type="file">` fields. Browser support section in the master branch's README hints that `FormData` is somehow supported, but I couldn't find any mentions of it in the documentation website. After blindly trying using `.field()` and `.append()`, I found out that it works with `.send()`.

Documented FormData support in .send()

---

docs/index.md

I spent several hours today figuring out why I was unable to pipe a file in a request to a Flask (or any Python WSGI) server, so I figured I would share that knowledge with everyone else.

docs(piping): add note about chunked transfer encoding

---

lib/node/index.js

Superagent has recently been upgraded to use version 2.0.3 of mime.
However, between version 1.4.1 and 2.0.3 of mime an earlier warning has been upgraded to an error when defining the same mime types twice .
See https://github.com/visionmedia/superagent/issues/1288 for a longer explanation

Fix for error in subsequent require() calls

---

lib/node/index.js
test/basic.js

This patch wraps `_isResponseOk` in a try/catch block and passes along the caught error. The client version of superagent already appears to be doing this properly.
Fixes #1247

Catch and pass along errors in ok callback

---

lib/client.js

`xhr.getAllResponseHeaders()` may actually return a header string without trailing `\r\n`.
Fixes #1295.

Don't pop last array element when parsing a header.

---

docs/index.md

According to the discussion in #283 as well as [the code in the latest release](https://github.com/visionmedia/superagent/blob/v3.7.0/lib/request-base.js#L230), 3xx responses are considered errors by default.
This PR increases clarity about this point in the docs.

Document that 3xx status codes are errors

---

lib/request-base.js
test/retry.js

The new retry feature is very useful, but there's no way to get any insight into which requests might be failing or why they need to be retried. I've added an optional callback parameter to `retry` so we can either report, log, or otherwise keep track of how or why retry is called for certain requests.
We're using superagent to send 100s of requests simultaneously, so knowing when we are falling into the retry logic is important. Hopefully others will find this useful as well.

Add optional callback to retry

---

lib/client.js
lib/node/index.js
test/request.js
test/support/server.js

There's an odd mimetype `json-seq` which is a delimited series of JSON
objects (see [RFC 7464](https://tools.ietf.org/html/rfc7464)).
This format is not parseable JSON, so `isJSON('application/json-seq')`
should return `false`.

Do not parse json-seq as json

---

lib/node/index.js

Hi!
Superagent is awesome and it allows to upload node Buffers like this `req.send(buffer)...` - this is exactly what we need. Unfortunately, `.on('progress', ...)` does not work in this case, this PR solves the problem.
Please let me know if you have any questions/considerations or see any issues.

[node] Emit progress event while uploading Buffer via send method

---

lib/request-base.js
test/client/request.js
test/form.js

Harsher version of #1153. Probably a breaking change.
Related to #1152
I suggest releasing warning version first, and the throwing version sometime later

Throw when using unsupported mix of send and field

---

lib/node/index.js

I need to make requests to a specific IP address. With HTTP that's easy:
```
request.get('http://1.2.3.4').set('Host', 'example.com')
```
but for HTTPS it currently fails, because TLS will be validated against `1.2.3.4` rather than `example.com`.
This change makes Host header (if set) take precedence over the URL.
Open questions:
- Is it secure?
- How to test it?

Set https.servername from Host header

---

lib/node/index.js
test/node/basic.js
test/node/buffers.js
test/node/exports.js

I often use superagent to make requests to API's returning XML responses. In order to parse the response body, I need to call the buffer() method everytime, which gets tedious. 
I added a buffer field on the superagent object so that you can define certain response-types to be buffered or not buffered by default. I don't believe that it is a breaking change, and I think it might be useful to both me and other users of superagent.

Allow default buffer settings based on response-type.

---

lib/node/index.js
test/client/serialize.js
test/node/query.js

Addresses #1367 as discussed. See the commit message for details.  I’m not that familiar with the superagent code base (especially around how code is shared between the Node and browser versions), so please let me know if you think this is missing anything. 
This PR leaves the behavior of `req.query(Object)` the same as it is now. I also worked up a [slightly different version](https://github.com/ethanresnick/superagent/commit/d4380735898076914e52887379b393aba0fa1167) that changes `req.query(Object)` to not encode any backticks provided in a key/value of the object. That approach has some pros and cons (also discussed in the commit message), but you can check out the code for it if you're curious. I think I slightly prefer this version, but I could probably go either way.

feat: Leave backticks unencoded in query strings where possible

---

lib/node/index.js
test/node/redirects.js
test/support/server.js

Cookies laid in a previous request were not being merged with a new request due to the header being `Cookie` rather than `cookie`. This uses the internal `_headers` object where keys are coerced to be lowercase to fix this.

Access cookie in headers correctly

---

package.json

This fixes an issue seen sometimes when using superagent in node.js. The an error is thrown when an agent is used and the server send invalid `Set-Cookie` headers. The package [x-ray](https://github.com/matthewmueller/x-ray), which relies on [x-ray-crawler](https://github.com/lapwinglabs/x-ray-crawler), which relies on superagent, has an example of this problem seen here: https://github.com/matthewmueller/x-ray/issues/234.

Update dependency 'cookiejar' to version 2.1.2

---

lib/node/index.js
test/node/serialize.js

`request.serialize(fn)` is not working in Node.  This patch uses user specified `_serializer` in case it exists.
Fixes #1141

fix req.serialize in node

---

.travis.yml
lib/node/http2wrapper.js
test/node/agency.js
test/node/https.js
test/node/inflate.js
test/node/network-error.js
test/node/pipe.js
test/node/query.js
test/node/redirects-other-host.js
test/node/response-readable-stream.js
test/node/set-host.js
test/node/toError.js
test/node/unix-sockets.js
test/support/express/index.js
test/support/express/requestDecorator.js
test/support/express/responseDecorator.js
test/support/express/utils.js
test/support/server.js

HTTP/2 with node 10 did not work, because we can not use setNoDelay with HTTP/2 socket.
This PR disable `request.setNoDelay` on http2.

Fix http2 request with node 10.

---

Readme.md

Simple plugin that adds cheerio to html responses, useful when testing server-side rendering with supertest.

Adding link to new cheerio plugin

---

lib/client.js
lib/request-base.js

Upload timer
https://github.com/visionmedia/superagent/pull/1375
New PR made from the discussion  about to add a new upload timer that could be triggered only in case of long Upload chunk delay if the deadline timer is off

Add upload timeout

---

lib/node/index.js
lib/request-base.js
test/node/multipart.js

This patch is fixing regression introduced by https://github.com/visionmedia/superagent/commit/6670a0fb708fef3d8e09538ee8af6c73f682f346, see https://github.com/visionmedia/superagent/issues/1466 for detailed discussion.
/cc @kornelski  @lapo-luchini
I have verified the fix by running the following test manually. ~~Please advise me how to capture these test cases in your automated test suite.~~
The first two use cases are already captured in the existing test suite, so I updated the existing tests to match the new behavior. Then I added two new tests to verify what happens when two errors are triggered by a single request (the last case below).
```js
// remote host is listening, attaching a missing file
// PROMISE VARIANT
require('.').post('http://example.com/does-not-exist') …
```

Fix handling of FormData errors

---

.gitignore
src/node/index.js
test/node/pipe.js

There is a bug in redirects during a pipe. If the request responds with a redirect status, but an empty Location header then superagent will throw `Uncaught TypeError: Cannot read property '_pipeContinue' of undefined`.
To reproduce you can checkout my tests (without the patch) and run them. You will see:
```bash
330 passing (8s)                               
5 pending                                
1 failing                                      
1) request pipe should not throw on bad redirects:          
Uncaught TypeError: Cannot read property '_pipeContinue' of undefined
at ClientRequest.req.once.res (lib/node/index.js:414:33)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:543:21)
at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
at …
```

Invalid redirect in pipe

---

src/client.js

Fixes #1481.
It seems we already have a [test case](https://github.com/visionmedia/superagent/blob/47f1d2829e5dfd4855a8fac5da388d6ed1067b86/test/client/serialize.js#L32) for this. However I didn't found how to run it.

fix: omit queries that are set to undefined

---

src/node/index.js
test/node/user-agent.js

Disable setting default user-agent

---

docs/index.md
package.json
src/agent-base.js
src/node/agent.js
src/node/index.js
test/node/https.js

Tackles Issue #926 by adding a new method `disableTLSCerts` to node client to allow bypassing TLS certificate checks.

Feature disable tls certs

---

Makefile
src/node/index.js

Use `res.getHeaders()` to avoid deprecation warning

---

src/client.js

Time to time I see my app throws "Unsuccessful HTTP response" error message when it got unsuccessful response even though a backend sent an error message. But sometimes it throws a  correct error that I got from the backend. After some investigation, I realized that sometimes there's no value in `res.statusText` but only `res.text` has one. For example, below both responses are from same API request. 
```
response: {
method: 'POST',
url: 'https://test.url/api/v1/createaccount',
data: { ... },
headers: { ... },
text: 'Unauthorized',
statusText: '', <-- has no value
statusCode: 401,
status: 401,
statusType: 4,
info: false,
ok: false,
clientError: true,
serverError: false,
...,
}
```
In this case, it always returns "Unsuccessful HTTP response" which is not a helpful message at all even …

Check res.text as well to return a better error txt message

---

src/agent-base.js
src/node/agent.js
src/node/index.js
test/node/secure-cookie.js

Allow overriding the default secure cookie for Cookie access info (use case: doing tests directly with express / koa app without nginx / tls certs)

feat: add secure cookie override to agent

---

src/client.js
test/client/serialize.js

I was having issues with an oData (https://www.odata.org/) based API. oData uses queries like
<http://example.com/todo?$skip=100&$top=50>
Superagent will currently encode this to <http://example.com/todo?%24skip=100&%24top=50>
According to HTTP spec this isn't technically correct. While values of query parameters should have fill encoding applied, the list of reserved characters is smaller for the overall URL.
A correct implementation would be to use encodeURIComponent over the query values and then encodeURI over the entire URL. However, the approach I've taken is equivalent.
Some of the answers to <https://stackoverflow.com/questions/4540753/should-i-use-encodeuri-or-encodeuricomponent-for-encoding-urls> provide some more explanation. I can provide full detail from HTTP and HTML specs …

Fix URI encoding

---

src/node/agent.js

This fixes the issue whereby if request.url is modified in a plugin for an agent (eg. superagent-prefix), cookies are not preserved across different requests, using that agent (see issue #1164).
This is fixed by simply executing agent._attachCookies() after agent._setDefaults().
Note: this is my first pull request ever.

fix: attach cookies to agent after plugin is used

---

src/node/index.js
src/request-base.js
test/node/basic.js

fix: allow unset to prevent default values for Content-Type and Accept-Encoding

---

src/request-base.js
test/retry.js

This PR is to enforce consistent `retry` behaviour for both  the`.end` and `.then` syntaxes.
The problem I'm trying to fix has been highlighted in these issues:
- https://github.com/visionmedia/superagent/issues/1487
- https://github.com/visionmedia/superagent/issues/1541
When using `.then` syntax in Node.js, we only want to abort a request if there are no retries or the  maximum number of retries has been exceeded.
Please review

fix: ensure node retries happen when using .then syntax (#1487)

---

docs/index.md
package.json
src/node/index.js
test/node/redirects.js

Allow for .connect({'*': {host: 'hostname', port: 12345}}) overrides to
change the destination port of a request.

feature: Support port overrides in connect()

---

.dist.babelrc
.dist.eslintrc
.lib.babelrc
.lib.eslintrc
docs/index.md
package.json
src/client.js
src/node/index.js
src/request-base.js

This PR adds new functionality:
- The ability to specify the callback of `.retry()` as an `async` function. The purpose is to enable `await`ing a Promise within the callback. This could be to used to fetch some external data, or by simply utilizing a setTimeout to resolve the promise after a specified delay. The result is that the .retry() is delayed by the given amount (or after the data is received). It does not break existing functionality i.e. the `.retry()` method can still be a normal synchronous function without any difference in behavior.
This PR also Resolves #1526 
- It prevents the `.retry()` method from being invoked on a successful request, and only allows it to invoke when there is a specified non-`null` error passed to `.callback()`

Improve .retry() method functionality with delays and prevent calling on successful request

---

docs/tail.html

This replaces an insecure version of jQuery (CVE-2020-11022) and will make it possible to fix issues raised by WhiteSource by updating to the next release.

Update jQuery in tail.html

---

src/client.js

Unifies behavior for Node and browser with regards to  'application/x-www-form-urlencoded'
Previous PR was #1589, but this is a better fix.

fix: use qs to serialize form data in browser

---

README.md

Note of the breaking change in browser 6.0 -> 6.1

---

package.json
src/node/index.js
yarn.lock

The Make file doesn't run tests correctly for me (with fresh clone with `yarn install && yarn test` or after changes with `yarn install && yarn test`) so unable to test locally - almost all of the tests fail with "Error: Forbidden" when I checkout the `master` branch
Edit: CI tests via Travis aren't running either as Travis shut down [travis-ci.org](https://travis-ci.org) back in June this year, so the project needs to move to [travis-ci.com](https://travis-ci.com) with limited open source credits (though they have [dubious security practises](https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/) of late) or switch to GitHub Actions.
Closes #1650 #1609

build: update formidable to 2.0.1

---

package.json

`!` is not supported by the semver library. This fixes a regression in v7
when used with engine-strict mode.
While the change in this PR may look similar to the state before #1660, 
it differs by using two pipe characters instead of one.
Fixes #1665.

package.json: fix invalid syntax in `engines`

---

docs/index.md

Hope this helps the next person, including future me, to not fall for this deprecated method again. :smiley: 
Great library! Thanks for all the effort that goes into this project!

Update Docs: req.header() is now req.set()

---

src/node/index.js
test/node/lookup.js

Add the feature of custom DNS resolve in node.
Sometime we use custom DNS to do service discovery, but superagent doesn't have the ability of changing the lookup method when call node's [http.request](https://nodejs.org/dist/latest-v12.x/docs/api/http.html#http_http_request_options_callback) method. 
So I pull this request to solve the problem.

feat: add lookup method

---

src/request-base.js

.field function is missing options to attach binary data.
Form-data has the function append(name, value, options) to attach binary data.
This change will add an option string (e.g. 'blob') and pass it to form-data, which will allow attaching binary data directly using .field function.
e.g. .field('mydataid', binary_data_buffer, 'blob')

Adding options to pass through form-data

---

package.json
test/content-type.js
test/node/pipe-redirect.js
test/node/serialize.js
test/support/express/index.js

Didn't fully disabled the prevent-abbreviations...
you tough `res` was ok, I'm fine with that...i think `args` is ok too... it's a good alternative to for not mixing up with arguments, the suggested `arguments_` with suffix is meh.

refactor: make linter happier

---

.gitignore
test/basic.js
test/node/multipart.js

We notice that there are some errors when run the testcases. There are three broken testcases in factly, each of them are smaill error.
I also find the travis-ci is not free now. The auto test is not triggered when new pull request is merged to master or new commit is push to master. I will make a pull request to switch travis-ci to github action.

fix: fixed the broken testcases

---

.dist.eslintrc
.eslintrc
.lib.eslintrc
package.json
src/client.js
test/client/request.js
test/node/toError.js

Superagent has three eslint configuration files. The `.lib.eslintrc` to valid the files under the directory of lib , the `.dist.eslintrc` to valid the files under the direcotry of dist, the property of `xo` of `package.json` to valid all the project's file.
For the issue of https://github.com/xojs/xo/issues/598 from xo ,we can not disable the rule for low version node check, such as the rule `node/no-unsupported-features/node-builtins`. So I just switch to use the native eslint, and add a new configuration file, named `.eslintrc`. This will also benefit for the vscode, when use the file `.eslintrc` , vscode can use the rules from it.
For current project not install the eslint plugin of `eslint-plugin-unicorn` in `package.json`. So I have not set it as an extendtion to `.eslintrc`. Someone …

fix: fixed the errors of eslint

---

.github/workflows/ci.yml
Makefile

I have done some work on bringing github action on current project. In the process of that, I also found some  problems.
First, the test on low version node is not supported now (https://github.com/yunnysunny/superagent/runs/4895023400). Since we use a newest  version of eslint (8.3.0 in fact), it will emit an error when we run it on node 10.x :
```
Oops! Something went wrong! :(
ESLint: 8.6.0
TypeError: Module.createRequire is not a function
at Object.<anonymous> (/home/runner/work/superagent/superagent/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2359:26)
at Module._compile (/home/runner/work/superagent/superagent/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load …
```

feat: add github action

---

src/client.js

Hey! This is basically a fix for the same issue as: https://github.com/visionmedia/superagent/pull/1612
But i did the change requested by @niftylettuce

use custom encoder if it is sent in option object

---

test/node/agency.js
test/node/flags.js
test/node/parsers.js

Part of #1779
Thinking of going trough one file/PR for easier review

test: replace should with node:assert

---

src/node/parsers/index.js

I'm going to try and [group export](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/group-exports.md) and put them at the bottom [last](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/exports-last.md) and also using explicit path (with extension) cuz this really makes it much more easier to refactor the code into ESM at a later stage.
It's much more easier to see what things gets exported when they are put last as a group

chore: use single export
